"""Write a fresh .env for the Compose setup: random passwords and four distinct tokens.

Standard library only.  Nothing generated is ever printed: the output names the file
and counts the variables.  An existing .env is not overwritten unless --force is given.
On POSIX the file is created with mode 600.  Model keys are not written here; set them
in the shell that runs docker compose (docs/operations.md).

Exit codes: 0 written, 2 refused (the file exists, or the target is not writable).
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import secrets
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_TARGET = PROJECT_ROOT / ".env"

PASSWORD_VARIABLES = (
    "POSTGRES_PASSWORD",
    "QUERYSHIELD_ADMIN_PASSWORD",
    "QUERYSHIELD_RO_PASSWORD",
)
TOKEN_VARIABLES = (
    "QUERYSHIELD_TOKEN_A_REQUESTER",
    "QUERYSHIELD_TOKEN_A_APPROVER",
    "QUERYSHIELD_TOKEN_B_REQUESTER",
    "QUERYSHIELD_TOKEN_B_APPROVER",
)
HEADER = (
    "# Generated by scripts/new_env.py. Local credentials: never commit or share this file.\n"
    "# Model keys are not stored here; set them in the shell that runs docker compose.\n"
)


def generate_values() -> dict[str, str]:
    """Three URL-safe passwords and four tokens that differ from each other."""

    values: dict[str, str] = {}
    for name in PASSWORD_VARIABLES:
        values[name] = secrets.token_urlsafe(24)
    tokens: set[str] = set()
    for name in TOKEN_VARIABLES:
        token = secrets.token_hex(24)
        while token in tokens:  # astronomically unlikely; the identity map needs distinct tokens
            token = secrets.token_hex(24)
        tokens.add(token)
        values[name] = token
    if len(set(values.values())) != len(values):
        raise RuntimeError("generated values are not all distinct")
    return values


def render(values: dict[str, str]) -> str:
    return HEADER + "".join(f"{name}={value}\n" for name, value in values.items())


def write_env(target: Path, *, force: bool) -> int:
    """Write the file; returns the number of variables.  Raises FileExistsError without force."""

    text = render(generate_values())
    flags = os.O_WRONLY | os.O_CREAT | (os.O_TRUNC if force else os.O_EXCL)
    descriptor = os.open(target, flags, 0o600)
    try:
        if os.name == "posix":
            os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            descriptor = -1
            handle.write(text)
    finally:
        if descriptor != -1:
            os.close(descriptor)
    return len(PASSWORD_VARIABLES) + len(TOKEN_VARIABLES)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--force", action="store_true", help="overwrite an existing .env")
    parser.add_argument("--path", type=Path, default=DEFAULT_TARGET, help="target file (default: .env in the project root)")
    args = parser.parse_args(argv)
    try:
        count = write_env(args.path, force=args.force)
    except FileExistsError:
        print(f"new_env_refused: {args.path.name} already exists; use --force to replace it")
        return 2
    except OSError as error:
        print(f"new_env_failed: {type(error).__name__}")
        return 2
    print(f"new_env_ok file={args.path.name} variables={count}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
